export interface CrmItem {
  section: string
  practice: string
  division: string
  id: string
  title: string
  status: "completed" | "in-progress" | "to-be-developed"
}

export const crmData: CrmItem[] = [
  // Section A - Practice Assurance
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "1",
    title: "Client Report Issuance",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "2",
    title: "Reissuance of Financial Statements",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "3",
    title: "Audit Captions tracker",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "4",
    title: "Audit Management Letter (RSM Kuwait Engage)",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "5",
    title: "Bank Confirmation request (RSM Kuwait Engage)",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "6",
    title: "CaseWare Archive request",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "7",
    title: "File to store request – Phase 1",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "8",
    title: "Data Analytics auto sharing result with Engagement Team",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "9",
    title: "IT and auto sharing result with Engagement Team",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "10",
    title: "Component companies - Phase 1",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "11",
    title: "Consultation as per RSM Orbs",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "12",
    title: "Letter to those charged with governance",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "13",
    title: "Task based budgeting",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "14",
    title: "Audit Committee Presentation",
    status: "to-be-developed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "15",
    title: "Component companies Phase 2 (Communication Workflow)",
    status: "to-be-developed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "16",
    title: "Data Analytics Workflow (Partner response for the follow up action)",
    status: "to-be-developed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "17",
    title: "Detailed File to Store workflow - Phase 2",
    status: "to-be-developed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "18.1",
    title: "Improvement of audit caption tracker: Checkmark on schedule",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "18.2",
    title: "Improvement of audit caption tracker: Looping (reject feature)",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "18.3",
    title:
      "Improvement of audit caption tracker: Total time consumed for each caption (As per budget vs actual spent and for each client)",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "18.4",
    title: "Improvement of audit caption tracker: Sub-caption",
    status: "completed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "19",
    title: "Link the Current magnifier to the auto audit",
    status: "to-be-developed",
  },
  {
    section: "A",
    practice: "Practice Assurance",
    division: "Assurance",
    id: "20",
    title: "Signing Partner Rotation Workflow",
    status: "to-be-developed",
  },

  // Section B - Practice Auto Tax
  {
    section: "B",
    practice: "Practice Auto Tax",
    division: "Tax",
    id: "1",
    title: "Deem Profit basis",
    status: "completed",
  },
  {
    section: "B",
    practice: "Practice Auto Tax",
    division: "Tax",
    id: "2",
    title: "Actual Profit Automation – Design completion – April 30",
    status: "to-be-developed",
  },
  {
    section: "B",
    practice: "Practice Auto Tax",
    division: "Tax",
    id: "3",
    title: "NLST & Zakat Calculation",
    status: "to-be-developed",
  },

  // Section C - Practice Consulting & Management
  {
    section: "C",
    practice: "Practice Consulting",
    division: "Risk",
    id: "1",
    title: "Management Letter – ICR (Risk)",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Consulting",
    division: "Risk",
    id: "2",
    title: "Client Report Issuance for AUP (Risk)",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "1",
    title: "Off Boarding - Farewell",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "2",
    title: "On Boarding Training",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "3",
    title: "Training Management",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "4",
    title: "Valuation Process – Two time a Year",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "5",
    title: "Engagement Annual Survey",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "6",
    title: "Employee Happiness Annual Survey",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "7",
    title: "360 Annual Survey",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "8",
    title: "Optimum Structure – Phase 1",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "9",
    title: "Employee Referral Program",
    status: "completed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "10",
    title: "Employee onboarding process",
    status: "in-progress",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "11",
    title: "Employee offboarding process – Phase 2",
    status: "in-progress",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "12",
    title: "Resource request workflow based on Optimum Structure – Phase 2",
    status: "in-progress",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "13",
    title: "Training request management by Trainer (Workflow)",
    status: "to-be-developed",
  },
  {
    section: "C",
    practice: "Practice Management",
    division: "Human Resource",
    id: "14",
    title: "4Policy",
    status: "to-be-developed",
  },

  // Section D - Practice Management
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "1",
    title: "Opportunity Management",
    status: "completed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "2",
    title: "Budgeting",
    status: "completed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "3",
    title: "E-signature Process Request",
    status: "completed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "4",
    title: "Resource planning",
    status: "completed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "5",
    title: "Timesheet",
    status: "completed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "6",
    title: "Dispatching",
    status: "completed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "7",
    title: "Graphic Design Request",
    status: "completed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "8",
    title: "Translation Request",
    status: "completed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "9",
    title: "Pop-up notification for pending tasks",
    status: "completed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "10",
    title: "Proposal",
    status: "to-be-developed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "11",
    title: "Engagement Letter",
    status: "to-be-developed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "12",
    title: "Opportunity Process & Controls",
    status: "to-be-developed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "13",
    title: "Typing pool automation",
    status: "to-be-developed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "14",
    title: "Enhancement of Pop-up notifications for pending tasks – Phase 2",
    status: "to-be-developed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "15",
    title: "Enhancement of Budgeting model",
    status: "to-be-developed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Operation",
    id: "16",
    title: "Approval Hub",
    status: "to-be-developed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Client experience",
    id: "1",
    title: "Voice of Client",
    status: "completed",
  },
  {
    section: "D",
    practice: "Practice Management",
    division: "Client experience",
    id: "2",
    title: "Implementation of Case Management in RSM Kuwait Engage",
    status: "in-progress",
  },
]
